spring:
  application:
    name: jingyao-ai-code-assistant-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_assistant?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    name: root
    password: Lhr20030514
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jingyao.jingyaoaicodeassistant.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
